url=https://team-4y6k.testit.software
privateToken=ZWQ4M0Vnc3FFZ0t6VlY0QjRO
projectId=01988a26-19e1-7780-ad8f-cf14696d43f9
configurationId=01988a26-1a05-74a3-a385-c7db6b762578
# testRunId={%TEST_RUN_ID%}
# testRunName={%TEST_RUN_NAME%}
adapterMode=2
automaticCreationTestCases=true
#automaticUpdationLinksToTestCases={}
certValidation=false
#importRealtime={}
#testIt=TEST_IT